### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by damingupup** [sandmanli/monitor-for-android#1]
手机型号 荣耀9
Android 9
EMUI 9.1.0
启动指令 :
`sh monitor.sh fps/ "SurfaceView - com.tencent.tmgp.supercell.brawlstars/com.supercell.titan.tencent.GameAppTencent#0"`
报错信息: 
monitor.sh[334]: [: 1: unexpected operator/operand
monitor.sh[334]: [: 0: unexpected operator/operand

**Comment by damingupup** [comment]
原因参数没有填全，建议对参数进行默认设置

**Comment by sandmanli** [comment]
参数是按照位置传入的，没做参数传入的解析，不需要包名传入可以加个双引号传入个空""，再有文件夹名别有特殊字符/
